import { type NextPage } from "next";
import Head from "next/head";
import Login from "~/components/login";
const Home: NextPage = () => {

    return (
        <>
            <Head>
                <title>Drive Club</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" w-full h-screen flex flex-col items-center justify-center gap-4">
                <h1>Driving Lesson Scheduling</h1>
                <Login />
            </main>
        </>
    );
};

export default Home;

