import { NextPageContext, type NextPage } from "next";
import Head from "next/head";
import Login from "~/components/login";

import { getSession } from "next-auth/react";
const Home: NextPage = () => {

    return (
        <>
            <Head>
                <title>Drive Club</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" w-full h-screen flex flex-col items-center justify-center gap-4">
                <h1>Driving Lesson Scheduling</h1>
                <Login />
            </main>
        </>
    );
};
export async function getServerSideProps(context: NextPageContext) {

    const session = await getSession(context)
    console.log(session)
    if (session) {
        return {
            redirect: {
                destination: '/lessons',
                permanent: false,
            },
        }
    }
    return { props: {} }

}

export default Home;

